### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Astra-RX** [Astra-RX/poi-navybase#1]
v4.0.0
- [ ] update to react 0.14
- [ ] add akashi repair timer
- [ ] compress layout ... again.
- [ ] using experimental immutable.js
